config/routes.rb
Rails.application.routes.draw do
  get 'schoolnews/new'

  root   'schoolnews#index'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    'users/show'
  get    'static_pages/home'
  get    'static_pages/help'
  get    'static_pages/about'
  get    '/news',    to: 'schoolnews#index'
  get    '/news?p=0',to: 'schoolnews#index'
  get    '/submit',  to: 'schoolnews#new'
  get    '/newcomments',to: 'comments#newcomments'
  get    '/item',    to: 'schoolnews#show'

  scope 'v0' do
    scope 'item' do
      get '/comments/:id', to: 'comments#show_json', defaults: { format: 'json' }
      get '/news/:id', to: 'schoolnews#show_json', defaults: { format: 'json' }
      post '/create', to: 'schoolnews#create_json', defaults: { format: 'json'}
    end
  end

  resources :users
  resources :schoolnews
  resources :comments

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/schoolnews.rb
class Schoolnews < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 10, maximum: 200}

  VALID_URL_REGEX = /(https?|ftp|file):\/\/[-A-Za-z0-9+&@#\/%?=~_|!:,.;]+[-A-Za-z0-9+&@#\/%=~_|]/i
  validates :source, format: {with: VALID_URL_REGEX, on: :create}, allow_nil: true, allow_blank: true  # Allow nil but if not empty, match regex
end

app/controllers/schoolnews_controller.rb
class SchoolnewsController < ApplicationController
  before_action :logged_in_user, only: [:new, :show, :create]
  skip_before_action :verify_authenticity_token, only: [:create_json]

  PAGE_NUM = 8

  def index
    @page_num = params[:p]
    @page_num = 0 if @page_num.nil?
    @page_num = @page_num.to_i

    # puts @page_num
    # render plain: @page_num
    @news_list = Schoolnews.order(created_at: :desc).offset(@page_num * PAGE_NUM).limit(PAGE_NUM)
    # puts @news_list
    # render plain: @news_list.length
  end

  def show
    @school_news = Schoolnews.find(params[:id])
    @comment = Comment.new
  end

  def show_json
    @school_news = Schoolnews.find_by(id: params[:id])
    # @comment = Comment.new

    respond_to do |format|
      if @school_news.nil?
        msg = { :Error => "News with id:#{params[:id]} can not be found" }
        format.json { render json: msg, status: :not_found }
      else
        format.json { render :show, status: :ok }
      end
    end
  end

  def new
    @school_news = Schoolnews.new
  end

  # if @user.save
  #   format.html { redirect_to @user, notice: 'User was successfully created.' }
  #   format.json { render :show, status: :created, location: @user }
  # else
  #   format.html { render :new }
  #   format.json { render json: @user.errors, status: :unprocessable_entity }
  # end
  #
  # if @school_news.save
  #   # 处理注册成功的情况
  #   flash[:success] = "Successfully sbumit a news"
  #   redirect_to schoolnews_index_path
  # else
  #   render 'new'
  # end
  def create
    @school_news = Schoolnews.new(school_news_params)

    respond_to do |format|
      if @school_news.save
        # 处理注册成功的情况
        format.html {
          flash[:success] = "Successfully sbumit a news"
          redirect_to schoolnews_index_path
        }
        format.json { render :show, status: :created, location: @school_news }
      else
        format.html { render 'new' }
        format.json { render json: @school_news.errors, status: :unprocessable_entity}
      end
    end
  end

  def create_json
    candidate_params = item_create_param
    # puts(candidate_params)

    if candidate_params[:type] == "news"
      # puts "news-----"
      news_params = { :title => candidate_params[:text],
                      :source => candidate_params[:source],
                      :author => candidate_params[:username] }
      @school_news = Schoolnews.new(news_params)
      respond_to do |format|
        if @school_news.save
          # render json: @school_news
          format.json { render :show, status: :created, location: @school_news }
        else
          # render json: @school_news.errors
          format.json { render json: @school_news.errors, status: :unprocessable_entity}
        end
      end
    elsif candidate_params[:type] == "comments"
      # puts "comment-----"
      commnet_params = { :content => candidate_params[:text],
                         :author => candidate_params[:username],
                         :schoolnews_id => candidate_params[:news_id] }
      @comment = Comment.new(commnet_params)
      respond_to do |format|
        if @comment.save
          # render json: @comment
          format.json { render "comments/show", status: :created, location: @comment }
        else
          # render json: @comment
          format.json { render json: @comment.errors, status: :unprocessable_entity}
        end
      end
    else
      respond_to do |format|
        msg = { :Error => "type:#{candidate_params[:type]} not support" }
        format.json { render json: msg, status: :not_acceptable}
      end
    end

    # return
    # @school_news = Schoolnews.new(school_news_params)
    # respond_to do |format|
    #   if @school_news.save
    #     # render json: @school_news
    #     format.json { render :show, status: :created, location: @school_news }
    #   else
    #     # render json: @school_news.errors
    #     format.json { render json: @school_news.errors, status: :unprocessable_entity}
    #   end
    # end
  end

  private

    def school_news_params
      params.require(:schoolnews).permit(:title, :source, :author)
    end

    def item_create_param
      params.permit(:username, :text, :type, :source, :news_id)
    end

    # 前置过滤器
    # 确保用户已登录
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

end

app/helpers/schoolnews_helper.rb
module SchoolnewsHelper
  def news_has_source?(news)
    if news.source.nil? || news.source == ''
      false
    else
      true
    end
  end

  def safe_source(news)
    safe_res = ''
    if news.source.nil? or news.source == ''
      safe_res
    else
      '(' + URI(news.source).host + ')'
    end
  end

  def safe_comments_counts(news)
    comments = news.comments.all
    if comments.nil?
      0
    else
      comments.length
    end
  end
end

app/views/schoolnews/_error_comments.html.erb
<% if :comment.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(:comment.errors.count, "error") %>.
    </div>
    <ul>
      <% :comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/schoolnews/_error_messages.html.erb
<% if @school_news.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@school_news.errors.count, "error") %>.
    </div>
    <ul>
      <% @school_news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/schoolnews/index.html.erb
<% provide(:title, 'Home Page '+@page_num.to_s) %>
<% _idx = @page_num * 8 %>

<div class="row">
  <% @news_list.each do |news|%>
    <div class="news">
      <p class="news-title">
        <%= _idx += 1 %> .  <%= link_to news.title, item_path(id: news.id) %> <%= link_to_if(news_has_source?(news), safe_source(news), news.source) %>
      </p>
      <p class="news-info">
        by <%= news.author %> <%= cal_time_before(news.created_at)+' ago' %> | <%= link_to pluralize(safe_comments_counts(news), 'comment'), item_path(id: news.id) %>
      </p>
    </div>
  <% end %>
</div>

<%= link_to 'More', '/news?p='+(@page_num + 1).to_s %>

app/views/schoolnews/new.html.erb
<%= provide(:title, "Submit a news") %>
<h1 class="section-title">Submit a news:</h1>
<%=	form_for(@school_news) do |f| %>
  <%= render 'schoolnews/error_messages' %>

  <%= f.label :title %>
  <%= f.text_area :title, class: 'form-control' %>

  <%= f.label "news source (optional)" %>
  <%= f.text_field :source, class: 'form-control' %>

  <%= f.hidden_field :author, value: current_user_name %>

  <%= f.submit "Create News", class: "btn btn-primary" %>
<% end %>

app/views/schoolnews/show.html.erb
<% provide(:title, @school_news.title) %>
<h1 class="section-title">News:</h1> <hr> <br>
<div class="row">
  <div class="news">
    <p class="news-title">
      <%= link_to @school_news.title, item_path(id: @school_news.id) %> <%= link_to_if(news_has_source?(@school_news), safe_source(@school_news), @school_news.source)%>
    </p>
    <p class="news-info">
      by <%= @school_news.author %> <%= cal_time_before(@school_news.created_at)+' ago' %> | <%= link_to pluralize(safe_comments_counts(@school_news), 'comment'), item_path(id: news.id) %>
    </p>
  </div>
</div>

<br>
<!--<h1 class="section-title">Leave a comment:</h1> <hr> <br>-->
<div class="row">
  <%#=	form_for(@school_news.comments.build) do |f| %> <!-- 千万别乱用这句话,会产生一个空的评论对象 -->
  <%= form_for(@comment) do |f| %>
    <%#= render 'schoolnews/error_comments' %>

    <%= f.label "Comments" %>
    <%= f.text_area :content, class: 'form-control' %>

    <%= f.hidden_field :author, value: current_user_name %>
    <%= f.hidden_field :schoolnews_id, value: @school_news.id %>

    <%= f.submit "Submit comment", class: "btn btn-primary" %>
  <% end %>
</div>

<br><br>
<h1 class="section-title">All comments:</h1> <hr>
<div class="row">
  <% if @school_news.comments.nil? || @school_news.comments.length == 0 %>
    No one comments here, go and leave a comment to be the first one!
  <% else %>
    <%= render @school_news.comments %>
  <% end %>
</div>