config/routes.rb
Rails.application.routes.draw do
  get 'schoolnews/new'

  root   'schoolnews#index'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    'users/show'
  get    'static_pages/home'
  get    'static_pages/help'
  get    'static_pages/about'
  get    '/news',    to: 'schoolnews#index'
  get    '/news?p=0',to: 'schoolnews#index'
  get    '/submit',  to: 'schoolnews#new'
  get    '/newcomments',to: 'comments#newcomments'
  get    '/item',    to: 'schoolnews#show'

  scope 'v0' do
    scope 'item' do
      get '/comments/:id', to: 'comments#show_json', defaults: { format: 'json' }
      get '/news/:id', to: 'schoolnews#show_json', defaults: { format: 'json' }
      post '/create', to: 'schoolnews#create_json', defaults: { format: 'json'}
    end
  end

  resources :users
  resources :schoolnews
  resources :comments

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="/">News App</a>
    by <a href="https://github.com/iViolinSolo">@ViolinSolo</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", static_pages_about_path %></li>
      <li><%= link_to "API", "https://github.com/pigfly/School-RAD/tree/master/assignment2" %></li>
      <!--<li><a href="http://news.railstutorial.org/">News</a></li>-->
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to image_tag("logo.png", alt: "News App", id: "logo-img"), "#" %>
    <%= link_to "News App", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Comments", newcomments_path %></li>
        <li><%= link_to "Submit", submit_path %></li>
        <% if logged_in? %>
          <!--<li><%#= link_to "Users", '#' %></li>-->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <div id="main-content">
      <%= render 'layouts/header' %>
      <div class="container">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
  </body>
</html>